{
 "title": "Banking - Team 3",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket[$__rate_interval])) by(path,method,status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(method, path, status) (rate(http_request_histogram_count{status=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count{path!=\"/metrics\"}[$__rate_interval])) by(path, method, status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Go Goroutines Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  }
 ]
}